const en2Jp = {
  'Thatch': 'わら',
  'Flint': '火打石',
  'Stone': '石',
  'Wood': '木材',
  'Hide': '皮',
  'Fiber': '繊維',
  'Metal Ingot': '金属のインゴット',
  'Steel Ingot': '鋼のインゴット',
  'Iron Ingot': '金属のインゴット',
  'Cementing Paste': 'セメント',
  'Sparkpowder': '発火粉',
  'Crystal': '水晶',
  'Oil': '原油',
  'Polymer': 'ポリマー',
  'Electronics': '電子基板',
  'Element': 'エレメント',
  'Black Pearl': '黒真珠',
  'Metal': '金属鉱石',
  'Iron': '金属鉱石',
  'Obsidian': '黒曜石',
  'Pelt': '毛皮',
  'Element Shard': 'エレメントシャード',
  'Leather': 'レザー',
  'Feathers': '羽毛',
  'Clay': '粘土',
  'Gunpowder': '火薬',
  'Beeswax': '蜜蝋',
  'Silica Pearls': 'シリカ真珠',
  'Silk': '絹',
  'Angler Gel': 'アンコウのジェル',
  'Keratin': 'ケラチン',
  'Chitin': 'キチン',
  'Absorbent Substrate': '吸収性基材',
  'Organic Polymer': '有機ポリマー',
  'Shell Fragment': 'シェル・フラグメント',
  'Narcoberry': 'ナルコベリー',
  'Spoiled Meat': '腐った肉',
  'Stimberry': 'スティムベリー',
  'LeechBlood': 'ヒルの血液',
  'Rare Flower': 'レアフラワー',
  'Rare Mushroom': 'レアマッシュルーム',
  'Narcotic': '麻酔薬',
  'Citronal': 'レモン',
  'Rockarrot': 'ニンジン',
  'Charcoal': '木炭',
  'Fertilizer': '肥料',
  'Sap': '樹液',
  'Chitin/Keratin': 'キチン',
  'Sulfur': '硫黄',
  'Green Gem': '緑の宝石',
  'Blue Gem': '青い宝石',
  'Red Gem': '赤い宝石',
  'Fungal Wood': '真菌のきのこ',
  'Stone Arrow': '石の矢',
  'Green Gem or Fragmented Green Gem': '緑の宝石',
  'Congealed Gas Ball': '凝固ガスボール',
  'Wood (or Fungal Wood)': '木材',
  'Gasbags bladder': 'ガスバッグの浮袋',
  'Polymer類': 'ポリマー',
  'Electronics(電子基板)': '電子基板',
  'Dried Tobacco': '乾燥タバコ',
  'Sand': '砂',
  'Glass': 'ガラス',
  'Crude Oil': '原油',
  'Carbon': '炭',
  'Limestone': '石灰石',
  'Lumber': '板材',
  'Element Dust': 'エレメントダスト',
  'Congealed Gas': '濃縮されたガス',
  'Fresh Firewood': '新鮮な薪',
  'Fresh Poultry': '生の鶏肉',
  'Raw Meat': '生肉',
  'Salt': '塩',
  'Raw Salt': '塩',
  'Claystone': '粘土岩',
  'Fresh Tobacco': '煙草（タバコ）',
  'Bio Toxin': 'バイオトキシン',
  'Ammonite Bile': 'アンモナイトの胆汁',
  'Gasoline': 'ガソリン',
  '': '',
};

module.exports = en2Jp;